### ISSUE TITLE
Can't test subroutines returning an empty string

### ISSUE THREAD

**Issue by choroba** [ingydotnet/test-base-pm#17]
If a subroutine returns an empty string, the input value is used in the test instead.

Sample (test "zero" shouldn't fail):

```
#!/usr/bin/perl
use warnings;
use strict;

use Test::Base tests => 2;

sub func {
    'X' x $_
}


run_is input => 'expected';

__END__
=== one
--- input func
1
--- expected chomp
X
=== zero
--- input func
0
--- expected chomp
```

**Comment by ingydotnet** [comment]
Greetings from the future (2018)!

The code seems to stem from https://github.com/ingydotnet/test-base-pm/blob/master/lib/Test/Base.pm#L637-L644

Which deals with using `$_` for filter simplicity which on the whole was probably a bad API design to go with.

The simple fix appears to be to change your filter to use:
```
$_  =  'X' x $_
```
In 2018 Test::Base has been replaced with a shiny new TestML. If you are still interested in Perl by then, check it out. :)
